Repository DeveloperAcademy-POSTECH/MacC-Team15-GearCo, pull requests merged in 2023-12, with the labels that each got.

#98 [Feat] Meal Detail View + Hifi 작업
  Solidner.xcodeproj/project.pbxproj
  Solidner/Literal/TextLiterals.swift
  Solidner/Models/Ingredient.swift
  Solidner/Models/MockPlanData.swift
  Solidner/ObservableObjects/MealOB.swift
  Solidner/ObservableObjects/MealPlansOB.swift
  Solidner/SolidnerApp.swift
  Solidner/Views/Components/ButtonComponents.swift
  Solidner/Views/Components/ToastMessage.swift
  Solidner/Views/Planning/AddPlan/AddTestIngredientsView.swift
  Solidner/Views/Planning/AddPlan/AddedIngredientView.swift
  Solidner/Views/Planning/AddPlan/MealDetailView.swift
  Solidner/Views/Planning/BatchSetting/PlanBatchSettingView.swift
  Solidner/Views/Planning/Common/ChangeMonthModal.swift
  Solidner/Views/Planning/Common/DailyPlanListView.swift
  Solidner/Views/Planning/Common/Modifier/DefaultHorizontalPadding.swift
  Solidner/Views/Planning/Common/RootVStack.swift
  Solidner/Views/Planning/MainView.swift
  Solidner/Views/Planning/Monthly/MonthlyPlanningView.swift
  Solidner/Views/Planning/StartPlan/StartPlanView.swift
  Solidner/Views/Planning/Weekly/PlanGroupDetailView.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
Labels: 🌟 Feature, 🎨 Design

#102 [Feat] Toast Message in 재료 추가 뷰
  Solidner.xcodeproj/project.pbxproj
  Solidner/Assets.xcassets/chevrons/Contents.json
  Solidner/Assets.xcassets/chevrons/headerChevron.imageset/Contents.json
  Solidner/Assets.xcassets/chevrons/headerChevron.imageset/headerChevron.svg
  Solidner/Assets.xcassets/chevrons/mypageChevron.imageset/Contents.json
  Solidner/Assets.xcassets/chevrons/mypageChevron.imageset/mypageChevron.svg
  Solidner/Assets.xcassets/chevrons/rightChevronSmall.imageset/Contents.json
  Solidner/Assets.xcassets/chevrons/rightChevronSmall.imageset/rightChevronSmall.svg
  Solidner/Assets.xcassets/chevrons/tinyChevron.imageset/Contents.json
  Solidner/Assets.xcassets/chevrons/tinyChevron.imageset/tinyChevron.svg
  Solidner/Views/Components/RootVStack.swift
  Solidner/Views/Components/ToastMessage.swift
  Solidner/Views/Planning/AddPlan/AddTestIngredientsView.swift
  Solidner/Views/Planning/AddPlan/MealDetailView.swift
  Solidner/Views/Planning/Common/PlanEmptyView.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
Labels: 🌟 Feature

#104 [Feat/#96]: swipe back gesture 구현
  Solidner.xcodeproj/project.pbxproj
  Solidner/Extension+/UINavigationController+.swift
Labels: 🌟 Feature

#107 [Feat/#97]: 이유식 전체 삭제 구현
  Solidner.xcodeproj/project.pbxproj
  Solidner/Network/FirebaseManager.swift
  Solidner/ObservableObjects/MealPlansOB.swift
  Solidner/Views/Planning/BatchSetting/PlanBatchSettingView.swift
Labels: 🌟 Feature

#112 Bug/#110 display date
  Solidner.xcodeproj/project.pbxproj
  Solidner/Extension+/Date+.swift
  Solidner/Literal/TextLiterals.swift
  Solidner/Views/Planning/Common/DisplayDateInfoView.swift
  Solidner/Views/Planning/MainView.swift
  Solidner/Views/Planning/Monthly/MonthlyPlanningView.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
Labels: 🐞 Bug

#114 [Feat/#113] 일부 화면 SE 기기대응, 회원정보 관련 기능 추가, 디자인 수정 등
  Solidner.xcodeproj/project.pbxproj
  Solidner/Network/FirebaseManager.swift
  Solidner/Views/Mypage/MypageRootView.swift
  Solidner/Views/Mypage/UserInfoUpdateView.swift
  Solidner/Views/Planning/Monthly/MonthlyPlanningView.swift
  Solidner/Views/Planning/StartPlan/StartPlanView.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
Labels: 🌟 Feature, 🎨 Design

#116 [Bug/#115] 첫째날에 주의 표시 안보이는 이슈 외
  Solidner/Extension+/Date+.swift
  Solidner/Literal/TextLiterals.swift
  Solidner/ObservableObjects/MealPlansOB.swift
  Solidner/ObservableObjects/UserOB.swift
  Solidner/Views/Components/TitleAndHintView.swift
  Solidner/Views/Planning/AddPlan/AddIngredientBigDivision.swift
  Solidner/Views/Planning/Weekly/PlanGroupDetailView.swift
Labels: 🐞 Bug
