Repository DeveloperAcademy-POSTECH/MacC-Team15-GearCo, pull requests merged in 2023-11, with the labels that each got.

#2 Feat/#1 Apple Login
  Solidner.xcodeproj/project.pbxproj
  Solidner/Network/FirebaseManager.swift
  Solidner/ObservableObjects/AppleLoginOB.swift
  Solidner/ObservableObjects/UserOB.swift
  Solidner/ObservableObjects/observable_dummy.swift
  Solidner/Solidner.entitlements
  Solidner/SolidnerApp.swift
  Solidner/Views/Onboarding/SignInView.swift
  Solidner/Views/views_dummy.swift
Labels: 🌟 Feature, 🛠️ Refactor, ⚙️ Setting

#6 Feat/#5 textliterals
  Solidner.xcodeproj/project.pbxproj
  Solidner/Literal/TextLiterals.swift
Labels: 🌟 Feature

#7 Weekly Planning View 틀 작업
  Solidner.xcodeproj/project.pbxproj
  Solidner/Literal/TextLiterals.swift
  Solidner/Views/Planning/Weekly/WeeklyPlanningDummy.swift
  Solidner/Views/Planning/Weekly/WeeklyPlanningView.swift
Labels: 🌟 Feature

#10 Feat/#9 AddPlanView 틀 작업 1
  Solidner.xcodeproj/project.pbxproj
  Solidner/Extension+/Date+.swift
  Solidner/Literal/TextLiterals.swift
  Solidner/Views/Planning/AddPlan/AddPlanView.swift
  Solidner/Views/Planning/Weekly/WeeklyPlanningView.swift
Labels: 🌟 Feature

#20 Feat/#9 Add Plan View 틀 작업
  Solidner.xcodeproj/project.pbxproj
  Solidner/Extension+/Image+.swift
  Solidner/Extension+/Shape+.swift
  Solidner/Literal/TextLiterals.swift
  Solidner/Views/Components/CycleGapSegmentedPicker.swift
  Solidner/Views/Components/ThickDivider.swift
  Solidner/Views/Components/TitleAndActionButtonView.swift
  Solidner/Views/Components/TitleAndHintView.swift
  Solidner/Views/Onboarding/AgreeToTermsView.swift
  Solidner/Views/Planning/AddPlan/AddPlanView.swift
  Solidner/Views/Planning/AddPlan/StartDateSettingModal.swift
Labels: 🌟 Feature

#27 Feat/#23 StartPlanView
  Solidner.xcodeproj/project.pbxproj
  Solidner/Extension+/View+.swift
  Solidner/Literal/TextLiterals.swift
  Solidner/Models/MockPlanData.swift
  Solidner/ObservableObjects/MealOB.swift
  Solidner/SolidnerApp.swift
  Solidner/Views/Onboarding/OnboardingEndView.swift
  Solidner/Views/Planning/AddPlan/MealDetailView.swift
  Solidner/Views/Planning/AddPlan/StartDateSettingModal.swift
  Solidner/Views/Planning/StartPlan/StartDateInitialSelectModal.swift
  Solidner/Views/Planning/StartPlan/StartPlanView.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
  Solidner/Views/Planning/Weekly/WeeklyPlanningView.swift
Labels: 🌟 Feature

#30 [Feat] Change Month Modal 작업함
  Solidner.xcodeproj/project.pbxproj
  Solidner/Literal/TextLiterals.swift
  Solidner/Views/Planning/Common/ChangeMonthModal.swift
Labels: 🌟 Feature

#32 [Feat] Plan Batch Setting View
  Solidner.xcodeproj/project.pbxproj
  Solidner/Literal/TextLiterals.swift
  Solidner/Models/CycleGaps.swift
  Solidner/Models/DisplayDateType.swift
  Solidner/ObservableObjects/MealOB.swift
  Solidner/ObservableObjects/UserOB.swift
  Solidner/Views/Components/SolidnerSegmentedPicker.swift
  Solidner/Views/Planning/AddPlan/MealDetailView.swift
  Solidner/Views/Planning/BatchSetting/PlanBatchSettingView.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
Labels: 🌟 Feature

#36 Feat/#33 daily plan list view
  Solidner.xcodeproj/project.pbxproj
  Solidner/Extension+/Color+.swift
  Solidner/Extension+/Image+.swift
  Solidner/Literal/TextLiterals.swift
  Solidner/Models/DisplayDateType.swift
  Solidner/ObservableObjects/UserOB.swift
  Solidner/Views/Planning/Common/DailyPlanListView.swift
  Solidner/Views/Planning/Common/DisplayDateInfoView.swift
  Solidner/Views/Planning/Common/MealGroupView.swift
  Solidner/Views/Planning/Common/WarningView.swift
  Solidner/Views/Planning/Weekly/MealGroupView.swift
  Solidner/Views/Planning/Weekly/PlanDetailView.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
Labels: 🌟 Feature

#41 Feat/#29 월간 플래닝 화면 제작
  Solidner/Extension+/Date+.swift
  Solidner/Extension+/View+.swift
  Solidner/SolidnerApp.swift
  Solidner/Views/Planning/Monthly/MonthlyPlanningView.swift
Labels: 🌟 Feature, 📝 Document, 🛠️ Refactor

#43 Feat/#39 plan list view hifi
  Solidner/Extension+/Text+.swift
  Solidner/Literal/TextLiterals.swift
  Solidner/Views/Components/SolidnerSegmentedPicker.swift
  Solidner/Views/Components/ThickDivider.swift
  Solidner/Views/Components/TitleAndHintView.swift
  Solidner/Views/Planning/BatchSetting/PlanBatchSettingView.swift
  Solidner/Views/Planning/Common/ChangeMonthModal.swift
  Solidner/Views/Planning/Common/DailyPlanListView.swift
  Solidner/Views/Planning/Common/MealGroupView.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
Labels: 🌟 Feature

#44 Feat/#42 AddIngredientsView 리팩토링 및 Hi-Fi에 따른 디자인 수정 완료
  Solidner.xcodeproj/project.pbxproj
  Solidner/Extension+/Color+.swift
  Solidner/Literal/TextLiterals.swift
  Solidner/Views/Planning/AddPlan/AddIngredientBigDivision.swift
  Solidner/Views/Planning/AddPlan/AddTestIngredientsView.swift
Labels: 🛠️ Refactor, 🎨 Design

#46 [Feat] plan detail view 외 Hifi 작업
  Solidner.xcodeproj/project.pbxproj
  Solidner/Assets.xcassets/background/Contents.json
  Solidner/Assets.xcassets/background/loginBackground.imageset/Contents.json
  Solidner/Assets.xcassets/background/loginBackground.imageset/loginBackground.svg
  Solidner/Assets.xcassets/background/loginBg.imageset/Contents.json
  Solidner/Assets.xcassets/background/loginBg.imageset/loginBg.png
  Solidner/Assets.xcassets/background/soCuteNameBackground.imageset/Contents.json
  Solidner/Assets.xcassets/background/soCuteNameBackground.imageset/soCuteNameBackground.png
  Solidner/Assets.xcassets/calendar.imageset/Contents.json
  Solidner/Assets.xcassets/calendar.imageset/calender.svg
  Solidner/Assets.xcassets/editDetail.imageset/Contents.json
  Solidner/Assets.xcassets/editDetail.imageset/editDetail.svg
  Solidner/Assets.xcassets/ingredientsInStart.imageset/Contents.json
  Solidner/Assets.xcassets/ingredientsInStart.imageset/ingredientsInStart.png
  Solidner/Assets.xcassets/ingredientsInStart.imageset/ingredientsInStart@2x.png
  Solidner/Assets.xcassets/ingredientsInStart.imageset/ingredientsInStart@3x.png
  Solidner/Assets.xcassets/rightChevronSmall.imageset/Contents.json
  Solidner/Assets.xcassets/rightChevronSmall.imageset/rightChevronSmall.svg
  Solidner/Assets.xcassets/userInfo.imageset/Contents.json
  Solidner/Assets.xcassets/userInfo.imageset/userInfo.svg
  Solidner/Extension+/Image+.swift
  Solidner/Info.plist
  Solidner/Literal/TextLiterals.swift
  Solidner/Models/MockPlanData.swift
  Solidner/Views/Components/CycleGapSegmentedPicker.swift
  Solidner/Views/Components/TitleAndHintView.swift
  Solidner/Views/Planning/Common/DailyPlanListView.swift
  Solidner/Views/Planning/Common/DraggableMealGroupView.swift
  Solidner/Views/Planning/Common/MealGroupView.swift
  Solidner/Views/Planning/StartPlan/StartDateInitialSelectModal.swift
  Solidner/Views/Planning/StartPlan/StartPlanView.swift
  Solidner/Views/Planning/Weekly/PlanDetailView.swift
Labels: 🌟 Feature

#49 [Feat] Meal Detail View Hifi 작업
  Solidner.xcodeproj/project.pbxproj
  Solidner/Assets.xcassets/check.imageset/Contents.json
  Solidner/Assets.xcassets/check.imageset/check.svg
  Solidner/Extension+/CGFloat+.swift
  Solidner/Extension+/Image+.swift
  Solidner/Extension+/Shape+.swift
  Solidner/Extension+/Text+.swift
  Solidner/Extension+/View+.swift
  Solidner/Literal/TextLiterals.swift
  Solidner/Models/MockPlanData.swift
  Solidner/ObservableObjects/MealOB.swift
  Solidner/Views/Components/TitleAndActionButtonView.swift
  Solidner/Views/Planning/AddPlan/AddedIngredientView.swift
  Solidner/Views/Planning/AddPlan/MealDetailView.swift
  Solidner/Views/Planning/AddPlan/StartDateSettingModal.swift
  Solidner/Views/Planning/Common/ColoredIngredientsText.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
Labels: 🌟 Feature

#52 Feat/#51 재료 raw데이터 추가 및 가공
  Solidner.xcodeproj/project.pbxproj
  Solidner/IngredientData.json
  Solidner/Models/Ingredient.swift
  Solidner/Models/MockPlanData.swift
  Solidner/Models/models_dummy.swift
  Solidner/Network/network_dummy.swift
  Solidner/ObservableObjects/IngredientData.swift
  Solidner/SolidnerApp.swift
  Solidner/Views/Planning/AddPlan/AddedIngredientView.swift
  Solidner/Views/Planning/Monthly/MonthlyPlanningView.swift
Labels: 🌟 Feature

#56 [Feat] plan navigation
  Solidner.xcodeproj/project.pbxproj
  Solidner/Assets.xcassets/calendarInMonthly.imageset/Contents.json
  Solidner/Assets.xcassets/calendarInMonthly.imageset/calendarInMonthly.svg
  Solidner/Assets.xcassets/calendarInPlanList.imageset/Contents.json
  Solidner/Assets.xcassets/calendarInPlanList.imageset/calendarInPlanList.svg
  Solidner/Extension+/Date+.swift
  Solidner/Extension+/Image+.swift
  Solidner/Literal/TextLiterals.swift
  Solidner/Models/MockPlanData.swift
  Solidner/ObservableObjects/MealOB.swift
  Solidner/ObservableObjects/MealPlansOB.swift
  Solidner/SolidnerApp.swift
  Solidner/Views/Components/Header.swift
  Solidner/Views/Onboarding/OnboardingEndView.swift
  Solidner/Views/Planning/AddPlan/MealDetailView.swift
  Solidner/Views/Planning/AddPlan/StartDateSettingModal.swift
  Solidner/Views/Planning/BatchSetting/PlanBatchSettingView.swift
  Solidner/Views/Planning/Common/ChangeMonthModal.swift
  Solidner/Views/Planning/Common/ColoredIngredientsText.swift
  Solidner/Views/Planning/Common/DailyPlanListView.swift
  Solidner/Views/Planning/Common/DraggableMealGroupView.swift
  Solidner/Views/Planning/Common/MealGroupView.swift
  Solidner/Views/Planning/Common/Modifier/DefaultHorizontalPadding.swift
  Solidner/Views/Planning/Common/RootVStack.swift
  Solidner/Views/Planning/StartPlan/StartDateInitialSelectModal.swift
  Solidner/Views/Planning/StartPlan/StartPlanView.swift
  Solidner/Views/Planning/Weekly/PlanDetailView.swift
  Solidner/Views/Planning/Weekly/PlanGroupDetailView.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
Labels: 🌟 Feature

#65 [Bug] 플랜 list view에서 재료 추가를 눌렀을 때, 전체 기본 설정대로 사이클이 변경되지 않는 버그
  Solidner/SolidnerApp.swift
  Solidner/Views/Planning/AddPlan/MealDetailView.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
Labels: 🐞 Bug

#71 [Feat] notice circle in date scroll
  Solidner.xcodeproj/project.pbxproj
  Solidner/Common/WrongPlanChecker.swift
  Solidner/Extension+/Date+.swift
  Solidner/Models/MockPlanData.swift
  Solidner/ObservableObjects/MealPlansOB.swift
  Solidner/SolidnerApp.swift
  Solidner/Views/Planning/AddPlan/MealDetailView.swift
  Solidner/Views/Planning/Common/DailyPlanListView.swift
  Solidner/Views/Planning/Weekly/PlanListView.swift
Labels: 🌟 Feature

#73 [Bug] Change month modal
  Solidner/Views/Planning/Common/ChangeMonthModal.swift
Labels: 🐞 Bug

#82 [Feat/#77] 재료 추가 화면 각종 기능 추가 - 1
  Solidner/Literal/TextLiterals.swift
  Solidner/Network/FirebaseManager.swift
  Solidner/Network/Network+.swift
  Solidner/SolidnerApp.swift
  Solidner/Views/Planning/AddPlan/AddIngredientBigDivision.swift
  Solidner/Views/Planning/AddPlan/AddTestIngredientsView.swift
  Solidner/Views/Planning/AddPlan/ReportIngredientModalView.swift
  Solidner/Views/Planning/Monthly/MonthlyPlanningView.swift
Labels: 🌟 Feature, 🪄 Update
